
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - PROJECT_NAME=FastAPI App
      - SECRET_KEY=changethisinsecuresecret
      - API_V1_STR=/api/v1
      - ACCESS_TOKEN_EXPIRE_MINUTES=11520
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000","http://localhost"]
      - ALGORITHM=HS256
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload